# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x08src.grpclocal\"u\n\x0fGenerateRequest\x12\x0c\n\x04json\x18\x01 \x01(\t\x12\x17\n\x0f\x64\x65ployment_name\x18\x02 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x03 \x01(\t\x12\x13\n\x0b\x61pi_version\x18\x04 \x01(\t\x12\x15\n\rauthorization\x18\x05 \x01(\t\"&\n\x10GenerateResponse\x12\x12\n\ntext_chunk\x18\x01 \x01(\t2S\n\x0cModelService\x12\x43\n\x08Generate\x12\x19.src.grpclocal.GenerateRequest\x1a\x1a.src.grpclocal.GenerateResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=25
  _globals['_GENERATEREQUEST']._serialized_end=142
  _globals['_GENERATERESPONSE']._serialized_start=144
  _globals['_GENERATERESPONSE']._serialized_end=182
  _globals['_MODELSERVICE']._serialized_start=184
  _globals['_MODELSERVICE']._serialized_end=267
# @@protoc_insertion_point(module_scope)
