version: 2
updates:
  - package-ecosystem: "pip"
    directory: "iris"
    schedule:
      interval: "weekly"
    groups:
      iris-python-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "memiris"
    schedule:
      interval: "weekly"
    groups:
      memiris-python-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
