repos:
  - repo: https://github.com/ddanier/sub-pre-commit.git
    rev: v4.1.0
    hooks:
      - id: iris-sub-pre-commit
        alias: iris
        name: "pre-commit for iris"
        args: ["-p", "iris"]
        files: "^iris/.*"
      - id: nebula-sub-pre-commit
        alias: nebula
        name: "pre-commit for nebula"
        args: ["-p", "nebula"]
        files: "^nebula/.*"
