version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - --api.dashboard=true # optional: Dashboard
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    ports:
      - "80:80"
      # - "8080:8080"  # optional: Dashboard http://localhost:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  auth:
    build:
      context: . # Projektroot
      dockerfile: docker/auth/Dockerfile
    environment:
      - NEBULA_SECRET=${NEBULA_SECRET}
    expose:
      - "9000"

  transcriber:
    build:
      context: .
      dockerfile: docker/transcriber/Dockerfile
    container_name: transcriber-service
    expose:
      - "5000"
    environment:
      - LLM_CONFIG_PATH=/app/llm_config.nebula.yml
    volumes:
      - ./llm_config.nebula.yml:/app/llm_config.nebula.yml:ro
      - ./temp:/app/temp
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.transcriber.rule=PathPrefix(`/transcriber`)
      - traefik.http.routers.transcriber.entrypoints=web
      # Service (interner Container-Port)
      - traefik.http.services.transcriber.loadbalancer.server.port=5000
      - traefik.http.middlewares.nebula-auth.forwardauth.address=http://auth:9000/authorize
      - traefik.http.middlewares.nebula-auth.forwardauth.trustforwardheader=true

  faq:
    build:
      context: .
      dockerfile: docker/faq/Dockerfile
    container_name: faq-service
    expose:
      - "5001"
    environment:
      - LLM_CONFIG_PATH=/app/llm_config.nebula.yml
    volumes:
      - ./llm_config.nebula.yml:/app/llm_config.nebula.yml:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.faq.rule=PathPrefix(`/faq`)
      - traefik.http.routers.faq.entrypoints=web
      - traefik.http.services.faq.loadbalancer.server.port=5001
      - traefik.http.middlewares.nebula-auth.forwardauth.address=http://auth:9000/authorize
      - traefik.http.middlewares.nebula-auth.forwardauth.trustforwardheader=true
