version: '3.9'

services:
  transcriber:
    build:
      context: .
      dockerfile: docker/transcriber/Dockerfile
    container_name: nebula-transcriber
    ports:
      - "5000:5000"
    environment:
      - APPLICATION_YML_PATH=/app/application_local.nebula.yml
      - LLM_CONFIG_PATH=/app/llm_config.nebula.yml
    volumes:
      - ./application_local.nebula.yml:/app/application_local.nebula.yml:ro
      - ./llm_config.nebula.yml:/app/llm_config.nebula.yml:ro
      - ./temp:/app/temp
    restart: unless-stopped
