version: "3.9"

services:
  transcriber:
    build:
      context: .
      dockerfile: docker/transcriber/Dockerfile
    container_name: nebula-transcriber
    ports:
      - "5050:5000"
    environment:
      - APPLICATION_YML_PATH=/app/application_local.nebula.yml
      - LLM_CONFIG_PATH=/app/llm_config.nebula.yml
    volumes:
      - ./application_local.nebula.yml:/app/application_local.nebula.yml:ro
      - ./llm_config.nebula.yml:/app/llm_config.nebula.yml:ro
      - ./temp:/app/temp
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: docker/gateway/Dockerfile
    container_name: ${GATEWAY_SERVICE_NAME}
    ports:
      - "8000:8000"
      - "${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}"
    environment:
      - TRANSCRIBE_SERVICE_URL=http://transcriber:5000
      - APPLICATION_YML_PATH=/app/application_local.nebula.yml
      - FAQ_SERVICE_NAME=${FAQ_SERVICE_NAME}
      - FAQ_SERVICE_PORT=${FAQ_SERVICE_PORT}
    volumes:
      - ./application_local.nebula.yml:/app/application_local.nebula.yml:ro
    depends_on:
      - transcriber
      - faq
    restart: unless-stopped

  faq:
    build:
      context: .
      dockerfile: docker/faq/Dockerfile
    container_name: ${FAQ_SERVICE_NAME}
    ports:
      - "${FAQ_SERVICE_PORT}:${FAQ_SERVICE_PORT}"
    environment:
      - APPLICATION_YML_PATH=/app/application_local.nebula.yml
      - LLM_CONFIG_PATH=/app/llm_config.nebula.yml
      - FAQ_SERVICE_PORT=${FAQ_SERVICE_PORT}
    volumes:
      - ./application_local.nebula.yml:/app/application_local.nebula.yml:ro
    restart: unless-stopped
