# nebula-dev.yml
services:
  transcriber:
    extends:
      file: nebula.yml
      service: transcriber
    image: ghcr.io/ls1intum/edutelligence/nebula-transcriber:${NEBULA_DOCKER_TAG}
    pull_policy: always
    restart: unless-stopped
    container_name: transcriber-service
    volumes:
      - ${NEBULA_LLM_CONFIG_FILE}:/app/llm_config.nebula.yml:ro
      - ${NEBULA_TEMP_DIR}:/app/temp
    environment:
      LLM_LOG_LEVEL: DEBUG

  faq:
    extends:
      file: nebula.yml
      service: faq
    image: ghcr.io/ls1intum/edutelligence/nebula-faq:${NEBULA_DOCKER_TAG}
    pull_policy: always
    restart: unless-stopped
    container_name: faq-service
    volumes:
      - ${NEBULA_LLM_CONFIG_FILE}:/app/llm_config.nebula.yml:ro
    environment:
      LLM_LOG_LEVEL: DEBUG

  nginx:
    extends:
      file: nebula.yml
      service: nginx
    restart: unless-stopped
    container_name: nginx-proxy
    volumes:
      - ${NEBULA_NGINX_CONFIG_FILE}:/etc/nginx/nginx.conf:ro
      - ${NEBULA_SSL_CERT}:/path/to/your/certificate.crt:ro
      - ${NEBULA_SSL_KEY}:/path/to/your/private.key:ro
