# nebula-dev.yml
services:
  traefik:
    extends:
      file: nebula.yml
      service: traefik
    ports:
      - "80:80"
  auth:
    extends:
      file: nebula.yml
      service: auth
    environment:
      LOG_LEVEL: DEBUG

  transcriber:
    extends:
      file: nebula.yml
      service: transcriber
    volumes:
      - ../llm_config.nebula.yml:/app/llm_config.nebula.yml:ro
      - ../temp:/app/temp
    environment:
      LLM_LOG_LEVEL: DEBUG

  faq:
    extends:
      file: nebula.yml
      service: faq
    volumes:
      - ../llm_config.nebula.yml:/app/llm_config.nebula.yml:ro
    environment:
      LLM_LOG_LEVEL: DEBUG

networks:
  nebula:
    driver: "bridge"
    name: nebula