"""
Abstract process handle protocol.

Both ``OllamaProcessHandle`` and ``VllmProcessHandle`` implement this
interface so that ``LaneManager`` can work with either backend without
conditionals.
"""

from __future__ import annotations

from typing import Any, AsyncIterator, Protocol, runtime_checkable

from logos_worker_node.models import LaneConfig, ProcessStatus


@runtime_checkable
class ProcessHandle(Protocol):
    """Interface that every backend process handle must implement."""

    lane_id: str
    port: int

    @property
    def lane_config(self) -> LaneConfig | None: ...

    async def init(self) -> None: ...
    async def close(self) -> None: ...
    async def spawn(self, lane_config: LaneConfig) -> ProcessStatus: ...
    async def stop(self) -> ProcessStatus: ...
    async def reconfigure(self, lane_config: LaneConfig) -> ProcessStatus: ...
    async def destroy(self) -> None: ...
    def status(self) -> ProcessStatus: ...

    # Model operations
    async def preload_model(self, model_name: str) -> bool: ...
    async def unload_model(self, model_name: str) -> bool: ...
    async def pull_model(self, model_name: str) -> bool: ...
    async def delete_model(self, model_name: str) -> bool: ...
    async def create_model(self, name: str, modelfile: str) -> bool: ...
    async def copy_model(self, source: str, destination: str) -> bool: ...
    async def show_model(self, model_name: str) -> dict[str, Any] | None: ...
    async def pull_model_streaming(self, model_name: str) -> AsyncIterator[dict[str, Any]]: ...
    async def get_loaded_models(self) -> list[dict[str, Any]]: ...
    async def get_version(self) -> str | None: ...
    async def get_available_models(self) -> list[dict[str, Any]]: ...

    # Optional sleep/wake controls (vLLM only; other backends may no-op).
    async def sleep(self, level: int = 1, mode: str = "wait") -> dict[str, Any]: ...
    async def wake_up(self) -> dict[str, Any]: ...
    async def is_sleeping(self) -> bool | None: ...
