services:
  hyperion:
    image: "ghcr.io/ls1intum/edutelligence/hyperion:${IMAGE_TAG}"
    environment:
      MODEL_NAME: ${MODEL_NAME}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_VERSION: ${OPENAI_API_VERSION}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      OLLAMA_BASIC_AUTH_USERNAME: ${OLLAMA_BASIC_AUTH_USERNAME}
      OLLAMA_BASIC_AUTH_PASSWORD: ${OLLAMA_BASIC_AUTH_PASSWORD}
      OLLAMA_HOST: ${OLLAMA_HOST}
    restart: unless-stopped
    ports:
      - '50051' # gRPC port
    networks:
      - shared-network
    healthcheck:
      test: ["CMD-SHELL", "cd /app/hyperion && poetry run health-check || exit 1"]
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    # Note: For gRPC services, we're not using Traefik HTTP routing
    # gRPC uses TCP and requires direct port access
    labels:
      - "traefik.enable=false"  # Disable Traefik for gRPC service

networks:
  shared-network:
    name: shared-network
    driver: bridge
