services:
  hyperion-dev:
    build:
      context: ../..
      dockerfile: hyperion/docker/Dockerfile.dev
      target: development
    working_dir: /app/hyperion
    env_file:
      - ../.env  # Load environment variables from .env file
    environment:
      # Core FastAPI settings
      PYTHONPATH: /app/hyperion:/app
      PYTHONUNBUFFERED: 1

      # Development defaults (can be overridden by .env file)
      API_KEY_HEADER: ${API_KEY_HEADER:-X-API-Key}
      API_KEY: ${API_KEY:-local-development-key}
      DISABLE_AUTH: ${DISABLE_AUTH:-true}

      # Note: All other environment variables (AI providers, tracing, etc.)
      # are loaded from .env file via the env_file directive above
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for hot reloading (only the app directory)
      - ../app:/app/hyperion/app
      # Mount shared library for hot reloading
      - ../../shared:/app/shared:ro
      # Keep Poetry cache persistent across container restarts
      - hyperion-poetry-cache:/root/.cache/pypoetry
    networks:
      - hyperion-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  hyperion-poetry-cache:
    driver: local

networks:
  hyperion-dev:
    driver: bridge
