import datetime

from iris.domain.chat.ask_user_chat.ask_user_chat_pipeline_execution_dto import (
    AskUserPipelineExecutionDTO,
)
from iris.domain.data.course_dto import CourseDTO
from iris.domain.data.programming_exercise_dto import ProgrammingExerciseDTO
from iris.domain.data.programming_submission_dto import ProgrammingSubmissionDTO
from iris.domain.data.result_dto import ResultDTO
from iris.domain.data.user_dto import UserDTO
from iris.domain.variant.ask_user_variant import AskUserVariant
from iris.pipeline.chat.iris_chat_mode import IrisChatMode

# The task/template/submission/tutor-question/answers every ask_user/
# assess_user_answer LLM test runs against. See
# helper/exercises/__init__.py::ACTIVE_EXERCISE to point the tests at a
# different exercise.
from tests.pipeline.chat.ask_user_pipeline.helper.exercises import (
    ACTIVE_EXERCISE as EXERCISE,
)

LLM_GENERATION_EVALUATION_PROMPT = """
You are an impartial and super strict jury member evaluating assessment questions about programming \
exercises generated by a chatbot.
The goal of these generated questions is to assess whether the students wrote the submissions to \
these exercises themselves.

Your task is to judge whether the generated assessment question is acceptable.
Use the given exercise context below to rate the question in context of the programming exercise.

Evaluation rules:
### 1. The question must be about the student’s own code

* Identify which parts of the code were written by the student by comparing the submission with \
the given code of the task.
* Base your question only on student-written elements.
* Do not ask about boilerplate, template code, or framework code.

### 2. The question must NOT ask about optional tasks

* Detect parts labeled as optional, bonus, extra, advanced, etc.
* Avoid any question whose topic intersects these optional sections.

### 3. The question must not be too easy

* Avoid trivial questions such as:

* “What does your function do?”
* “What is the name of this variable?”
* “Did you sort the list?”
* Prefer questions that require understanding of the implementation, e.g.:

* “Why do you update this variable inside the loop instead of before it?”
* “Explain the logic behind the condition in your second loop.”
* “How does your swapping mechanism ensure the array stays sorted?”

### 4. Ask about only one concept

* Focus on exactly one part of the implementation.
* Do not combine multiple topics.

### 5. No hints, no explanations

* Generate only the question, without hints or commentary.


## Exercise Context
- **Problem Statement:** {{ task }}
- **Code Template:** {{ template }}
- **Submitted Code:** {{ code }}

You must follow these rules strictly:
- If the assessment question is acceptable, respond with: !ok!
- If the assessment question is unacceptable, respond with: !bad!
- After !ok! or !bad!, add exactly ONE short sentence explaining your decision.
- Do NOT output anything else.
- Do NOT add formatting, markdown, bullet points, or multiple sentences.
- Do NOT mention the rules themselves.

Your entire output must follow exactly this format:
!ok! <one short sentence explanation>
OR
!bad! <one short sentence explanation mentioning the property of the five that was decisive>
"""

LLM_PAIRWISE_DIVERSITY_PROMPT = """
You are an impartial and super strict jury member evaluating assessment questions about programming \
exercises written by a tutor.
The goal of these generated questions is to assess whether the students wrote the submissions to \
these exercises themselves.

Your task is to judge whether the topics of the two questions given in the last user message are \
sufficiently different from each other.
* It is important that the two questions cover different concepts, instead of both covering the same \
small structure like a loop or a conditional branch.
* It is important that the second question cannot be answered using parts of the answer to the first \
one.
Use the given exercise context to rate the two questions in relation to each other and to the \
programming exercise.

## Exercise Context
- **Problem Statement:** {{ task }}
- **Code Template:** {{ template }}
- **Submitted Code:** {{ code }}

You must follow these rules strictly:
- If the two questions are sufficiently diverse, respond with: !ok!
- If the two questions are not sufficiently diverse (too similar / overlapping), respond with: !bad!
- After !ok! or !bad!, add exactly ONE short sentence explaining your decision.
- Do NOT output anything else.
- Do NOT add formatting, markdown, bullet points, or multiple sentences.
- Do NOT mention the rules themselves.

Your entire output must follow exactly this format:
!ok! <one short sentence explanation>
OR
!bad! <one short sentence explanation>
"""


DTO = AskUserPipelineExecutionDTO(
    programmingExerciseSubmission=ProgrammingSubmissionDTO(
        id=1,
        date=datetime.datetime(2026, 1, 11),
        repository=EXERCISE.code,
        isPractice=False,
        buildFailed=False,
        latestResult=ResultDTO(
            completionDate=datetime.datetime(2026, 1, 10), successful=True
        ),
    ),
    programmingExercise=ProgrammingExerciseDTO(
        id=1,
        title=EXERCISE.title,
        programmingLanguage=EXERCISE.programming_language,
        templateRepository=EXERCISE.template,
        problemStatement=EXERCISE.task,
    ),
    course=CourseDTO(id=1, name="Intro to Programming", description=None),
    settings=None,
    user=UserDTO(id=1, firstName="Random", lastName="User", memirisEnabled=False),
    minQuestions=0,
    maxQuestions=0,
    questionsAsked=0,
    chatMode=IrisChatMode.EXERCISE,
)

VARIANT = AskUserVariant(
    variant_id="ask_user_v1",
    name="Ask User",
    description="Variants used in tests",
    agent_model="oai-gpt-5.5",
    guide_model="oai-gpt-5.5",
    assessment_model="oai-gpt-5.5",
)

FIRST_MESSAGE_TIME = datetime.datetime(2026, 1, 1, 12, 0, 0)

USER_ANSWER = "I do not know."
