pyris:
  cache:
    hazelcast:
      host: localhost
      port: 5701
  api_keys:
    - token: "secret"
      comment: "DUMMY"
      llm_access:
        - DUMMY

  llms:
    DUMMY:
      type: "openai"
      name: "Dummy model"
      description: "Dummy model for testing"
      spec:
        context_length: 100
      llm_credentials:
        api_base: ""
        api_type: ""
        api_version: ""
        deployment_id: ""
        model: "gpt-3.5-turbo"
        token: ""
