name: pyris
version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - pyris

networks:
  pyris:
