name: "🐛 Bug Report"
description: Something in Edutelligence is not working as expected? Create a report to help us improve.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report.
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened? Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: "Steps to reproduce the behavior:"
      value: |
        1. Step one
        2. Step two
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: input
    attributes:
      label: Which version of Edutelligence are you seeing the problem on?
      description: The version helps us to narrow down the issue?.
    validations:
      required: true
  - type: dropdown
    id: service-selection
    attributes:
      label: What service is this bug related to?
      multiple: true
      options:
        - Athena
        - Atlas
        - Iris
        - Other/Unsure
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What module is this bug related to?
      multiple: true
      options:
        - Assessment Module Manager
        - Modeling LLM
        - Programming APTED
        - Programming LLM
        - Programming ThemisML
        - Text CoFee
        - Text LLM
        - Playground
        - Other (specify in "Additional context")
    validations:
      required: true
    if: service-selection contains "Athena"
  - type: dropdown
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Microsoft Edge
        - Firefox
        - Other (specify in "Additional context")
    if: service-selection contains "Athena"
  - type: input
    attributes:
      label: Operating System
      description: The operating system you're using. E.g. Windows 11, macOS Sonoma, Ubuntu 20.04, etc.
    if: service-selection contains "Athena"
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: Thanks for completing our form! Please click the "Submit new issue" button below to submit your bug report.
