[tool.poetry]
name = "log-viewer"
version = "2.7"
description = "Shows the logs of the assessment module manager and all modules in a web interface."
authors = ["Paul Schwind <paul.schwind@tum.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.14.*"
fastapi = "0.141.1"
uvicorn = "0.52.3"
docker = "7.2.0"
#mypy = "1.18.2"

[tool.poetry.group.dev.dependencies]
types-requests = "2.33.0.20260712"
prospector = { version = "1.19.1", extras = ["with_mypy"] }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
