name: Deploy to Pyris Production

on:
  workflow_dispatch:
    inputs:
      docker-tag:
        description: 'Docker tag to deploy (e.g. 1.0.0 or latest, default: latest)'
        required: true
        default: 'latest'
      branch-name:
        description: 'Branch name to deploy (default: main)'
        required: true
        default: 'main'

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      docker-tag: latest
      branch-name: main
      environment-name: Iris Production
      environment-url: https://pyris.artemis.cit.tum.de
    secrets: inherit