name: Lint & Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Cache Poetry virtualenv
      uses: actions/cache@v1.2.1
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Install Dependencies
      run: |
        poetry install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Execute black
      run: poetry run black . --check

    - name: Execute flake8
      run: |
        poetry run flake8 .

    - name: Start cache service
      run: docker compose up -d --build cache

    - name: Test with pytest
      run: poetry run pytest
