services:
  app:
    image: "ghcr.io/ls1intum/edutelligence/hyperion:${IMAGE_TAG-latest}"
    environment:
      # Model configuration
      MODEL_NAME: ${MODEL_NAME}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_VERSION: ${OPENAI_API_VERSION}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      OLLAMA_BASIC_AUTH_USERNAME: ${OLLAMA_BASIC_AUTH_USERNAME}
      OLLAMA_BASIC_AUTH_PASSWORD: ${OLLAMA_BASIC_AUTH_PASSWORD}
      OLLAMA_HOST: ${OLLAMA_HOST}
      
      # TLS configuration for production
      TLS_ENABLED: ${TLS_ENABLED:-false}
      TLS_CERT_PATH: ${TLS_CERT_PATH:-}
      TLS_KEY_PATH: ${TLS_KEY_PATH:-}
      TLS_CA_PATH: ${TLS_CA_PATH:-}
      
      # gRPC server settings
      GRPC_HOST: "0.0.0.0"
      GRPC_PORT: 50051
      GRPC_MAX_WORKERS: ${GRPC_MAX_WORKERS:-10}
    restart: unless-stopped
    ports:
      - "8080:50051/tcp"  # Explicitly TCP for gRPC
    volumes:
      # Mount TLS certificates (create ./certs directory first)
      - ./certs:/certs:ro
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:50051"]
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
