# Local development compose override
# Usage: docker-compose -f compose.local.yaml up
services:
  app:
    build:
      context: ..
      dockerfile: hyperion/Dockerfile
    ports:
      - "50051:50051/tcp"  # Explicitly TCP for gRPC
    env_file:
      - .env