"""Audio processing utilities using FFmpeg."""

import os
import subprocess  # nosec B404
from typing import List

from iris.common.logging_config import get_logger
from iris.tracing import observe

logger = get_logger(__name__)


@observe(name="Split Audio")
def split_audio_ffmpeg(
    audio_path: str, output_dir: str, chunk_duration: int = 900
) -> List[str]:
    """
    Split an audio file into chunks using FFmpeg.

    Audio is converted to MP3 format optimized for speech recognition:
    - 64k bitrate (small file size, good for speech)
    - 16kHz sample rate (Whisper's expected rate)
    - Mono channel

    Args:
        audio_path: Path to the input audio file.
        output_dir: Directory to save the audio chunks.
        chunk_duration: Duration of each chunk in seconds (default: 900 = 15 min).

    Returns:
        List of paths to the generated chunk files, sorted by name.

    Raises:
        RuntimeError: If FFmpeg fails or no chunks are generated.
    """
    os.makedirs(output_dir, exist_ok=True)

    # Clean old chunks if any exist
    for f in os.listdir(output_dir):
        if f.endswith(".mp3"):
            os.remove(os.path.join(output_dir, f))

    filename_base = os.path.splitext(os.path.basename(audio_path))[0]
    output_template = os.path.join(output_dir, f"{filename_base}_%03d.mp3")

    command = [
        "ffmpeg",
        "-i",
        audio_path,
        "-f",
        "segment",
        "-segment_time",
        str(chunk_duration),
        "-acodec",
        "libmp3lame",  # MP3 encoder
        "-b:a",
        "64k",  # Small size, still good for speech
        "-ar",
        "16000",  # 16 kHz for Whisper
        "-ac",
        "1",  # Mono
        output_template,
        "-y",
    ]

    logger.info("Splitting audio: %s (chunk_duration=%ds)", audio_path, chunk_duration)

    try:
        subprocess.run(
            command,
            shell=False,
            capture_output=True,
            text=True,
            check=True,
        )  # nosec B603

        chunk_files = sorted(
            [
                os.path.join(output_dir, f)
                for f in os.listdir(output_dir)
                if f.endswith(".mp3")
            ]
        )

        if not chunk_files:
            raise RuntimeError("No chunks were generated by FFmpeg.")

        logger.info("Created %d chunks in %s", len(chunk_files), output_dir)
        return chunk_files

    except subprocess.CalledProcessError as e:
        logger.error("FFmpeg audio split failed: %s", e.stderr)
        raise RuntimeError(f"FFmpeg audio split failed: {e.stderr}") from e
