[tool.poetry]
name = "llm_core"
version = "3.0"
description = "SHared LLM module."
authors = ["Felix Dietrich <felixtj.dietrich@tum.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.14.*"
athena = { path = "../athena", develop = true }
langsmith = "0.14.7"
langchain = "1.4.4"
langchain-ollama = "1.1.0"
langchain-openai = "1.7.0"
openai = "3.28.0"
python-dotenv = "1.2.4"
tiktoken = "0.14.0"
#langfuse = "^3.3.0"

[tool.poetry.scripts]
module = "athena:run_module"

[tool.poetry.group.dev.dependencies]
prospector = { version = "1.19.1", extras = ["with_mypy"] }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
