import logging
import os
import subprocess  # nosec B404

from nebula.tracing import trace_subprocess

logger = logging.getLogger(__name__)


def split_audio_ffmpeg(audio_path, output_dir, chunk_duration=60):
    os.makedirs(output_dir, exist_ok=True)

    # Clean old chunks
    for f in os.listdir(output_dir):
        if f.endswith(".mp3"):
            os.remove(os.path.join(output_dir, f))

    filename_base = os.path.splitext(os.path.basename(audio_path))[0]
    output_template = os.path.join(output_dir, f"{filename_base}_%03d.mp3")

    command = [
        "ffmpeg",
        "-i",
        audio_path,
        "-f",
        "segment",
        "-segment_time",
        str(chunk_duration),
        "-acodec",
        "libmp3lame",  # MP3 encoder
        "-b:a",
        "64k",  # small size, still ok for speech
        "-ar",
        "16000",  # 16 kHz for Whisper
        "-ac",
        "1",  # mono
        output_template,
        "-y",
    ]

    logger.info("Splitting audio using FFmpeg: %s", audio_path)

    with trace_subprocess(
        "Split Audio (ffmpeg)",
        command,
        {"audio_path": audio_path, "chunk_duration": chunk_duration},
    ) as span:
        try:
            subprocess.run(
                command, shell=False, capture_output=True, text=True, check=True
            )  # nosec B603

            chunk_files = sorted(
                [
                    os.path.join(output_dir, f)
                    for f in os.listdir(output_dir)
                    if f.endswith(".mp3")
                ]
            )

            if not chunk_files:
                span.end(success=False, error="No chunks were generated by FFmpeg")
                raise RuntimeError("No chunks were generated by FFmpeg.")

            span.end(
                success=True,
                output={"chunk_count": len(chunk_files)},
            )

        except subprocess.CalledProcessError as e:
            span.end(
                success=False,
                output={"returncode": e.returncode},
                error=e.stderr,
            )
            raise RuntimeError(f"FFmpeg audio split failed: {e.stderr}") from e

    logger.info("Created %s chunks in %s", len(chunk_files), output_dir)
    return chunk_files
