from __future__ import annotations

from enum import Enum


class Features(str, Enum):
    CHAT = "CHAT"
    COMPETENCY_GENERATION = "COMPETENCY_GENERATION"
    INCONSISTENCY_CHECK = "INCONSISTENCY_CHECK"
    TUTOR_SUGGESTION = "TUTOR_SUGGESTION"
    REWRITING = "REWRITING"
    LECTURE_INGESTION = "LECTURE_INGESTION"
    FAQ_INGESTION = "FAQ_INGESTION"
    AUTONOMOUS_TUTOR = "AUTONOMOUS_TUTOR"


CRITICAL_PIPELINES: set[Features] = {
    Features.CHAT,
}
