from __future__ import annotations

from enum import Enum


class Features(str, Enum):
    PROGRAMMING_EXERCISE_CHAT = "PROGRAMMING_EXERCISE_CHAT"
    COURSE_CHAT = "COURSE_CHAT"
    TEXT_EXERCISE_CHAT = "TEXT_EXERCISE_CHAT"
    LECTURE_CHAT = "LECTURE_CHAT"
    # COMPETENCY_GENERATION = "COMPETENCY_GENERATION"
    # REWRITING = "REWRITING"
    # INCONSISTENCY_CHECK = "INCONSISTENCY_CHECK"
    # TUTOR_SUGGESTION = "TUTOR_SUGGESTION"
    # LECTURE_INGESTION = "LECTURE_INGESTION"
    FAQ_INGESTION = "FAQ_INGESTION"


CRITICAL_PIPELINES: set[Features] = {
    Features.PROGRAMMING_EXERCISE_CHAT,
    Features.COURSE_CHAT,
    Features.TEXT_EXERCISE_CHAT,
    Features.LECTURE_CHAT,
}
