policy = {
        "id": 1,
        "entity_id": 1,
        "name": "strict",
        "description": "Strict Data Policy",
        "threshold_privacy": "CLOUD_NOT_IN_EU_BY_US_PROVIDER",
        "threshold_latency": 50,
        "threshold_accuracy": 60,
        "threshold_cost": 40,
        "threshold_quality": 60,
        "priority": 0,
        "topic": None,
    }

models = [
    {
        "id": 1,
        "name": "gpt-4o",
        "endpoint": "",
        "api_id": 1,
        "weight_privacy": "CLOUD_IN_EU_BY_US_PROVIDER",
        "weight_latency": 80,
        "weight_accuracy": 70,
        "weight_cost": 80,
        "weight_quality": 60,
        "tags": "",
        "parallel": 2,
    },
    {
        "id": 2,
        "name": "gpt-4",
        "endpoint": "",
        "api_id": 2,
        "weight_privacy": "CLOUD_NOT_IN_EU_BY_US_PROVIDER",
        "weight_latency": 70,
        "weight_accuracy": 90,
        "weight_cost": 70,
        "weight_quality": 80,
        "tags": "",
        "parallel": 2,
    },
    {
        "id": 3,
        "name": "gemma3:27b",
        "endpoint": "",
        "api_id": 3,
        "weight_privacy": "LOCAL",
        "weight_latency": 60,
        "weight_accuracy": 60,
        "weight_cost": 100,
        "weight_quality": 70,
        "tags": "",
        "parallel": 2,
    },
]