services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - shared-network
    depends_on:
      atlasml:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:80/health']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '5'

  atlasml:
    image: 'ghcr.io/ls1intum/edutelligence/atlasml:${IMAGE_TAG}'
    env_file:
      - .env
    environment:
      PYTHONPATH: ${PYTHONPATH:-/atlasml}
      WEAVIATE_HOST: ${WEAVIATE_HOST:-http://weaviate-test.ase.cit.tum.de/}
      WEAVIATE_PORT: ${WEAVIATE_PORT:-80}
      WEAVIATE_GRPC_PORT: ${WEAVIATE_GRPC_PORT:-443}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_URL: ${OPENAI_API_URL:-https://ase-se01.openai.azure.com}
      ATLAS_API_KEYS: ${ATLAS_API_KEYS:-["SuperSecureKey"]}
      SENTRY_DSN: ${SENTRY_DSN:-https://8fe7eac930933ea3c83ff7a66555de18@sentry.aet.cit.tum.de/6}
      ENV: ${ENV:-production}
    restart: unless-stopped
    expose:
      - '8000'
    networks:
      - shared-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/api/v1/health']
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: '5'

networks:
  shared-network:
    name: shared-network
    driver: bridge
