# ----------------------------------------------------------------------------------------------------------------------
# Setup for a Pyris server suitable for internal network requests (without nginx).
# ----------------------------------------------------------------------------------------------------------------------
# It is designed to take in environment variables for configuration, similar to the production setup.
# ----------------------------------------------------------------------------------------------------------------------

services:
  pyris-app:
    extends:
      file: ./pyris.yml
      service: pyris-app
    image: ghcr.io/ls1intum/edutelligence/iris:${PYRIS_DOCKER_TAG:-latest}
    pull_policy: always
    restart: unless-stopped
    volumes:
      - ${PYRIS_APPLICATION_YML_FILE}:/config/application.yml:ro
      - ${PYRIS_LLM_CONFIG_YML_FILE}:/config/llm_config.yml:ro
    ports:
      - "${PYRIS_PORT:-8000}:8000"
    networks:
      - pyris

  weaviate:
    extends:
      file: ./weaviate.yml
      service: weaviate
    ports:
      - "${WEAVIATE_PORT:-8001}:8001"
      - "${WEAVIATE_GRPC_PORT:-50051}:50051"
    networks:
      - pyris

networks:
  pyris:
    driver: "bridge"
    name: pyris
