name: Athena Documentation

on:
  pull_request:
    paths:
    - 'athena/docs/**'
    - '.github/workflows/athena_docs.yml'
  push:
    branches:
    - main
    tags: '[0-9]+.[0-9]+.[0-9]+'
    paths:
    - 'athena/docs/**'
    - 'athena/athena/athena/**' # Function docstrings might change
    - 'athena/assessment_module_manager/assessment_module_manager/**' # Function docstrings might change
    - '.github/workflows/athena_docs.yml'
  release:
    types:
    - created

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "athena/docs/"
        build-command: make html dirhtml
    - uses: actions/upload-artifact@v4
      with:
        name: Documentation
        path: athena/docs/_build/html/
    - uses: actions/upload-pages-artifact@v3
      with:
        path: athena/docs/_build/dirhtml/
      
  # Deployment job
  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: "https://ls1intum.github.io/Athena"
    runs-on: ubuntu-latest
    needs: docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
