name: Documentation

on:
  push:
    branches:
    - main
    paths:
    - 'atlas/docs/**'
    - '.github/workflows/atlas_docs.yml'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v6
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: atlas/docs/package-lock.json
    - name: Install dependencies
      run: |
        cd atlas/docs
        npm ci
    - name: Build documentation
      run: |
        cd atlas/docs
        npm run build
    - uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: atlas/docs/build/

  # Deployment job
  deploy:
    environment:
      name: atlas-documentation
      url: "https://docs.atlas.ase.cit.tum.de"
    runs-on: ubuntu-latest
    needs: docs
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: public
      - name: Copy site to server
        uses: appleboy/scp-action@master
        with:
          host: docs.atlas.ase.cit.tum.de
          username: ${{ vars.DOCS_SSH_USER }}
          key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          proxy_host: ${{ vars.DEPLOYMENT_GATEWAY_HOST }}
          proxy_username: ${{ vars.DEPLOYMENT_GATEWAY_USER }}
          proxy_key: ${{ secrets.DEPLOYMENT_GATEWAY_SSH_KEY }}
          proxy_port: ${{ vars.DEPLOYMENT_GATEWAY_PORT }}
          source: "public"
          target: ${{ vars.DOCS_HOME }}
      - name: Move site to www
        uses: appleboy/ssh-action@master
        with:
          host: docs.atlas.ase.cit.tum.de
          username: ${{ vars.DOCS_SSH_USER }}
          key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          proxy_host: ${{ vars.DEPLOYMENT_GATEWAY_HOST }}
          proxy_username: ${{ vars.DEPLOYMENT_GATEWAY_USER }}
          proxy_key: ${{ secrets.DEPLOYMENT_GATEWAY_SSH_KEY }}
          proxy_port: ${{ vars.DEPLOYMENT_GATEWAY_PORT }}
          script: |
              rm -rf ${{ vars.DOCS_WWW }}/*
              mv -f public/* ${{ vars.DOCS_WWW }}/
