name: Hyperion - Deploy to Test

on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: "Image tag to deploy (default: pr-<number> if PR exists, latest for default branch)"
      deploy-hyperion:
        type: boolean
        default: true
        description: (Re-)deploys hyperion.
      deploy-proxy:
        default: false
        type: boolean
        description: (Re-)deploys the proxy components. Usually not necessary and might cause downtime.

jobs:  
  deploy-hyperion:
    if: ${{ inputs.deploy-hyperion }}
    uses: ls1intum/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: hyperion-test1
      docker-compose-file: "./docker/compose.hyperion.yaml"
      main-image-name: ls1intum/edutelligence/hyperion
      image-tag: ${{ inputs.image-tag }}
      deployment-base-path: "/opt/hyperion"
    secrets: inherit

  deploy-proxy:
    if: ${{ inputs.deploy-proxy }}
    uses: ls1intum/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: hyperion-test1
      docker-compose-file: "./docker/compose.proxy.yaml"
      # We just keep the main-image-name and image-tag as placeholders
      main-image-name: ls1intum/edutelligence/hyperion
      image-tag: ${{ inputs.image-tag }}
      deployment-base-path: "/opt/proxy"
    secrets: inherit
  