name: Hyperion - Deploy to Test 1

on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: "Image tag to deploy (default: pr-<number> if PR exists, latest for default branch)"

jobs:  
  deploy-app:
    uses: ls1intum/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: "Hyperion - Test 1"
      docker-compose-file: "./hyperion/compose.yaml"
      main-image-name: ls1intum/edutelligence/hyperion
      image-tag: ${{ inputs.image-tag }}
      deployment-base-path: "/opt/hyperion"
    secrets: inherit