---
name: Logos - Test

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "logos/**"
      - "shared/**"
      - ".github/workflows/logos_test.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "logos/**"
      - "shared/**"
      - ".github/workflows/logos_test.yml"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Link shared dependency
        run: ln -s ../shared logos/shared

      - name: Install Dependencies
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install .
          uv pip install "coverage[toml]"
        working-directory: logos

      - name: Clean old coverage data
        run: |
          rm -f .coverage
          rm -f coverage.xml
        working-directory: logos

      - name: Run Tests
        run: |
          source .venv/bin/activate
          coverage run -m pytest
        working-directory: logos

      - name: Generate Coverage Report
        run: |
          source .venv/bin/activate
          coverage xml
        working-directory: logos
