---
name: Logos Webservice - Test

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "logos/logos-webservice/**"
      - ".github/workflows/logos_webservice_test.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "logos/logos-webservice/**"
      - ".github/workflows/logos_webservice_test.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "26"
          distribution: "temurin"
          cache: "maven"
          cache-dependency-path: logos/logos-webservice/pom.xml

      - name: Run Tests
        run: mvn -B test
        working-directory: logos/logos-webservice
